# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # to pip against the `main` branch
    target-branch: "main"
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"
